version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://dind:2375  # Point Jenkins to the DinD service
      - DOCKER_CERT_PATH=/certs/client  # Corrected formatting
      - DOCKER_TLS_VERIFY=1  # Corrected formatting
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker  # This line is not needed
    ports:
      - 8080:8080

networks:
  jenkins:

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
